import './globals.css'
import { Inter } from 'next/font/google'
import Nav from './nav'
import Footer from './footer'
// import soup from './Supper/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}





export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        

        <Nav></Nav>
        {children}
        <Footer></Footer>
        
      </body>
    </html>
  )
}
